name: Documentation
on:
  push:
    branches:
      - main
      - docs
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@v2.3.4
         
       - name: Setup Python
         uses: actions/setup-python@v2.2.2
         with:
            python_version: 3.x
         
       - name: Install Dependencies
         run: |
              pip install mkdocs-material
         
       - name: Build Documentation
         run: mkdocs build dist
         
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
